### ISSUE TITLE
Latest LocalyticsXamarin nuget package relies on Xamarin.Forms and LocalyticsSample projects

### ISSUE THREAD

**Issue by justintoth** [localytics/localytics-xamarin#52]
Since my original ticket was closed even though the issue still exists, I'm creating a new one with the same details... It's disappointing that I reported this 6 months ago and no one has taken it seriously, it shows that there is absolutely no one using Xamarin and Localytics. Furthermore, it's clear that the Localytics developers don't understand the difference between native Xamarin iOS / Xamarin Android apps and Xamarin Forms apps.

I just removed all nuget packages from my Xamarin iOS Project to start fresh re-adding them to the project file itself instead of using a packages.json file. When I added the LocalyticsXamarin nuget package (5.8.0), it gave build errors related to a LocalyticsXamarinForms.cs file:

```
/Users/justintoth/.nuget/packages/localyticsxamarin/5.8.0/contentFiles/any/any/LocalyticsXamarinForms.cs(20,20): Error CS0234: The type or namespace name 'Forms' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?) (CS0234) (com.rpr.mobile.ios.lib)
/Users/justintoth/.nuget/packages/localyticsxamarin/5.8.0/contentFiles/any/any/LocalyticsXamarinForms.cs(7,7): Error CS0246: The type or namespace name 'LocalyticsSample' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (com.rpr.mobile.ios.lib)
/Users/justintoth/.nuget/packages/localyticsxamarin/5.8.0/contentFiles/any/any/LocalyticsXamarinForms.cs(71,71): Error CS0246: The type or namespace name 'IPlatform' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (com.rpr.mobile.ios.lib)
```

When inspecting this file, it depends on including the Xamarin.Forms nuget package, which doesn't make sense when working on a vanilla Xamarin.iOS project. It also relies on LocalyticsSample, which isn't found so obviously isn't being included in the nuget package. Can someone please resolve these issues and release a buildable LocalyticsXamarin nuget package?

**Comment by thomasvidas** [comment]
We have release version 6.0.3 which should fix the issue with LocalyticsXamarinForms. It will be released on nuget later today

**Comment by justintoth** [comment]
@thomasvidas Unfortunately I can't test your fix because so many breaking changes have been introduced since version 5.8.1 (the last one that worked before the Xamarin Forms regression.) LocalyticsSDK.SharedInstance doesn't even exist anymore, even though it's still shown in the GettingStarted guide.
